// <auto-generated />
namespace CRME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Doc_apoyo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Doc_apoyo));
        
        string IMigrationMetadata.Id
        {
            get { return "202404231527142_Doc_apoyo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
