// <auto-generated />
namespace CRME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class catalogo_Per : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catalogo_Per));
        
        string IMigrationMetadata.Id
        {
            get { return "202405092034374_catalogo_Per"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
